set(_CATKIN_CURRENT_PACKAGE "imu_3dm_gx4")
set(imu_3dm_gx4_MAINTAINER "gcross <gcross.code@icloud.com>")
set(imu_3dm_gx4_DEPRECATED "")
set(imu_3dm_gx4_VERSION "0.0.2")
set(imu_3dm_gx4_BUILD_DEPENDS "diagnostic_updater" "geometry_msgs" "roscpp" "sensor_msgs" "geometry_msgs" "galt_common")
set(imu_3dm_gx4_RUN_DEPENDS "message_runtime" "diagnostic_updater" "geometry_msgs" "roscpp" "sensor_msgs" "galt_common")
set(imu_3dm_gx4_BUILDTOOL_DEPENDS "catkin" "message_generation")